version: "3"

services:
  db:
    image: postgis/postgis:15-3.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: FoodDeliveryDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
